# tomcat 8
#FROM tomcat:8-jdk11-temurin

# tomcat 9
FROM tomcat:9-jdk11-temurin

# tomcat 10
#   tomcat10 で SpringBoot は現状動かない
#     - https://github.com/spring-projects/spring-boot/issues/22414
#FROM tomcat:jdk11-temurin

WORKDIR /usr/local/tomcat/webapps/
COPY ./demo/target/demo.war  /usr/local/tomcat/webapps/